# Generated by Django 5.2.7 on 2025-10-20 19:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('customer_address', models.TextField(verbose_name='Dirección del Cliente')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto/Servicio')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En Proceso'), ('shipped', 'Enviada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=15, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
    ]
